--- #YAML:1.0
name:               Apache-Session-libmemcached
version:            0.01
abstract:           An implementation of Apache::Session using
author:
    - Javier Uruen Val <jval@venda.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache::Session:      0
    Memcached::libmemcached:  0
    Test::MockObject:     0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
